### ISSUE TITLE
Is it possible to add a parameter (tag) to the buffer before to be sent?

### ISSUE THREAD

**Issue by macscripter** [jcrugzz/buffr#3]
Dear Jarrett,

I really appreciate your great support!

Look, I would like to modify the data before to be sent to the target. Let's suppose that I need to add a new field in the data: <extra_field>100</extra_field>

Should I do it using the buffer?

Here goes my code:

var http = require('http'),
httpProxy = require('http-proxy'),
proxy = httpProxy.createProxyServer({});  
var miTarget='web:CountryName';
var inicio = '<'+miTarget+'>';
var fin = '</'+miTarget+'>';
var buffr = require('buffr');

var server = http.createServer(function(req, res) {
var miTag = '';
var buf = req.pipe(buffr());   // Here, using buffr library I should copy the req as I understand....
buf.extra_field='100'  // should I add the new parameter here?

req.on('data', function (data) {
// here I recover the parameter I need...
 miTag=data.toString().split(inicio)[1].split(fin)[0];

});

 req.on('end', function () {
 console.log('miTag:'+miTag);
  // After I got the parameter I want to proxy to a server depending on the parameter's value....
  if(miTag=='Portugal') {
   proxy.web(req, res, {target: 'http://www.webservicex.net',buffer:buf});
  }
    else {
    proxy.web(req, res, {target: 'http://other/host',buffer:buf}); 
  }
    });  
});

console.log("listening on port 80")
server.listen(80);

**Comment by jcrugzz** [comment]
You would need to create another stream that understands the structure of the type of data you are getting in the request in order to add a tag. `buffr` will not be able to do that for you because it cannot assume the structure of your request. I suggest you read up more on [`streams`](https://github.com/substack/stream-handbook) and write one that would be able to add a tag into the structure of the data you are receiving before buffering it.

**Comment by macscripter** [comment]
It is a bit hard.... You meand that before the code:

 var buf = req.pipe(buffr());

I need to change the req (adding a new tag) with streams, right?

Best regards

2015-11-23 1:17 GMT+00:00 Jarrett Cruger notifications@github.com:

**Comment by jcrugzz** [comment]
@macscripter yes, that would be the cleanest way to encapsulate the logic.

You would just need to implement this `AddTagStream` using [`through2`](https://github.com/rvagg/through2) or your standard [`TransformStream`](https://nodejs.org/dist/v4.2.2/docs/api/stream.html#stream_class_stream_transform_1) depending on your needs. Example of what it might look like is below

``` js
var buf = req.pipe(new AddTagStream(tag)).pipe(buffr());

```

**Comment by macscripter** [comment]
Jarrett,

Thank you for your support!

Unsing the through2 and supposing that I only need to change the data for a
body:

var body = '<myTag>BLAHBLAH</myTag>';

 var buf = req.pipe(through2.obj(function(obj, enc, next) {
       //this.push(obj.contents.toString());
       this.push(body);
       next();
    })).pipe(buffr());

and after passing it to

```
req.on('end', function () {
proxy.web(req, res, {target: 'http://localhost:9953',buffer:buf});
});
```

I still with the same problem...

Where am I wrong?

Thank you for helping me....

2015-11-23 16:06 GMT+00:00 Jarrett Cruger notifications@github.com:

**Comment by jcrugzz** [comment]
@macscripter you cannot pipe a `binary` stream to an objectMode stream. I cannot help you beyond this as I cannot write the code for you, you just have to sit down and figure out how the mechanics work. Good luck!

**Comment by macscripter** [comment]
Thank you, Jarrett. I am sure that with tips I will resolve this problem.

Best regards

2015-11-23 17:26 GMT+00:00 Jarrett Cruger notifications@github.com:

**Comment by macscripter** [comment]
Dear Jarrett,

I read your suggestions and finally I wrote this code:

  var util = require('util');
    var Transform = require('stream').Transform;

```
function changeData(options) {
if (!(this instanceof changeData))
return new changeData(options);

Transform.call(this, options);
}

util.inherits(changeData, Transform);

changeData.prototype._transform = function (chunk, enc, cb) {
chunk = chunk.toString().replace('LU0Request64','ALEXEI'); // let's
```

suppose that I need to change this tag
    console.log('new chunk:'+chunk);
    this.push(chunk);
    cb();
    };

So in this case the execution would be:

var buf  = req.pipe( new changeData()).pipe(buffr());

But when I pass the buf to:

proxy.web(req, res, {target: 'http://localhost:9953',buffer:buf});

I don't get any response from server.... But when I pass the original
chunk, everything is OK.

I know that I disturb you a lot but I really tried to code it well....
I think I miss something but I don't understand what. Could you only guide
me with a little comment?

I really appreciate your important support, Jarrett.

Best regards

2015-11-23 17:40 GMT+00:00 Alex Pavlov macscripter@gmail.com:

**Comment by jcrugzz** [comment]
@macscripter ahh yes so the issue here is that steams implicitly do a `process.nextTick` if that stream executes `synchronously`. Its one of the reasons that `buffr` is implemented differently than your standard `TransformStream`. I suggest following a similar implementation as I have chosen for `buffr` with the same logic that you put in the `TransformStream` and it should work. Implement your transform logic within [here](https://github.com/jcrugzz/buffr/blob/master/index.js#L48-L51) and listen for the `pipe` event just like I do so you can read the data directly from the stream and avoid the need for creating an unnecessary `nextTick`

**Comment by macscripter** [comment]
Jarrett, I am not sure but I think that the problem is different....

I noticed that when I replace with the same size, everything is OK.
for example: chunk.toString().replace('JARRETT','ALEX111')  //original size
= 7, final size = 7

I got:

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema">
soap:Body
<CONVERS2_x002F_1 xmlns="urn:APTLU0WS.APT.pragmasis.pt">
<env>
<Timeout xmlns="urn:DataTypes.APT.pragmasis.pt">0</Timeout>
</env>
<LU0Applid>TEST</LU0Applid>
<LU0Request64>ALEX111</LU0Request64>
<LU0Timeout>60</LU0Timeout>
</CONVERS2_x002F_1>
/soap:Body
/soap:Envelope

But when I replace  chunk.toString().replace('JARRETT','ALEX111222')
 //original size = 7, final size = 10
I got:

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema">
soap:Body
<CONVERS2_x002F_1 xmlns="urn:APTLU0WS.APT.pragmasis.pt">
<env>
<Timeout xmlns="urn:DataTypes.APT.pragmasis.pt">0</Timeout>
</env>
<LU0Applid>TEST</LU0Applid>
<LU0Request64>ALEX111222</LU0Request64>
<LU0Timeout>60</LU0Timeout>
</CONVERS2_x002F_1>
/soap:Body
</soap:Envelo

With the "broken" final tag: instead of /soap:Envelope now it is
</soap:Envelo

So I think that the problem is the "fixed size structure" I need to keep
when I perform replacement....

But I don't know how to "adjust" the structure....

Anyway, you were a great support, Jarrett, and learned a lot with your help!

2015-11-25 16:18 GMT+00:00 Jarrett Cruger notifications@github.com:

**Comment by jcrugzz** [comment]
@macscripter ahh i misread. That is very interesting. I think what you need to do is take advantage of the  `_flush` method that you can implement with `TransformStream` to ensure you get the full content before the stream ends. This should allow you to make sure all the content is allowed to flow through the stream. I'm sure you can figure it out :). Cheers.

**Comment by macscripter** [comment]
Yes, I already started with that. I will let you know!

Warmest regards

2015-11-25 17:41 GMT+00:00 Jarrett Cruger notifications@github.com:

**Comment by macscripter** [comment]
Dear Jarrett,

Even with _flush I got the same result. That's is, with _flush I can add
everything at the end. But the fixed size seems to not be changed. If I
replace with "less size", I will have space to add more flushing. If not
(exactly the same size replacement) the flush will not take any effect
because of the "fixed structure".

I suspect that the problem is here:

 proxy.web(req, res, {target: 'http://localhost:9953', buffer:buf});

I mean that the "req" object should be "by size" exactly the same as the
buffer object.... So maybe the problem comes from the proxy library....

Interesting issue that is clearly out of the topic we started to discuss
due to my issue. :)

Warmest regards

2015-11-25 17:52 GMT+00:00 Alex Pavlov macscripter@gmail.com:

**Comment by jcrugzz** [comment]
@macscripter ahh so the problem has to do with the need to update the `content-length` header that is most likely set on the request object. that would make sense. You just need to update the value or set it on the request being proxied with the `proxyReq` event. You can get the new `content-length` of your request by emitting a `length` event (or something similar) from your `ChangesData` stream and using that value to set the `content-length` of the request you are proxying.

**Comment by macscripter** [comment]
Bingo, my friend! Welcome to Portugal / Spain to meet you personally!

Now I just need to adjust dinamically the size (based on my replacements)
before to proxy. But now the problem is absolutely clear!!!!!
Thank you a lot!

Warmest regards

2015-11-25 18:07 GMT+00:00 Jarrett Cruger notifications@github.com:
